services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campeonato-app
    environment:
      - NODE_ENV=production
      - PORT=3004
    ports:
      - "3004:3004"
    restart: unless-stopped
    networks:
      - tanstack-network

networks:
  tanstack-network:
    driver: bridge
